---
- name: Mount file systems
  hosts: all
  become: true
  vars_files:
    - data.yaml

  tasks:

    - name: Create a new ext4 primary partition
      community.general.parted:
        device: /dev/sdb
        number: 1
        state: present
        fs_type: ext4

    - name: Format the spare partition
      community.general.filesystem:
        fstype: ext4
        dev: /dev/sdb1

    - name: Mount the spare partition on acto dir
      ansible.posix.mount:
        path: "/var/lib/docker"
        fstype: ext4
        src: /dev/sdb1
        state: mounted

    - name: Get the home directory
      become: false
      command: echo $HOME
      register: home

    - name: create work dir
      become: false
      ansible.builtin.file:
        path: "{{ home.stdout }}/workdir"
        state: directory

    - name: Change ownership of acto dir
      ansible.builtin.file:
        path: "{{ home.stdout }}/workdir"
        mode: "u=rwx,g=rwx,o=rwx"
        state: directory
